/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutEchartsRouteImport } from './routes/layout-echarts'
import { Route as EfxChartsStreamingRouteImport } from './routes/efx-charts-streaming'
import { Route as EfxChartsRouteImport } from './routes/efx-charts'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BasicEchartsRouteImport } from './routes/basic-echarts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LabStreamingDataEchartsRouteImport } from './routes/lab/streaming-data-echarts'
import { Route as LabStreamingDataRouteImport } from './routes/lab/streaming-data'
import { Route as ExamplesSalesAnalyticsRouteImport } from './routes/examples/sales-analytics'
import { Route as ExamplesPerformanceRouteImport } from './routes/examples/performance'
import { Route as ExamplesOperationsRouteImport } from './routes/examples/operations'
import { Route as ExamplesMarketingRouteImport } from './routes/examples/marketing'
import { Route as ExamplesFinancialRouteImport } from './routes/examples/financial'

const LayoutEchartsRoute = LayoutEchartsRouteImport.update({
  id: '/layout-echarts',
  path: '/layout-echarts',
  getParentRoute: () => rootRouteImport,
} as any)
const EfxChartsStreamingRoute = EfxChartsStreamingRouteImport.update({
  id: '/efx-charts-streaming',
  path: '/efx-charts-streaming',
  getParentRoute: () => rootRouteImport,
} as any)
const EfxChartsRoute = EfxChartsRouteImport.update({
  id: '/efx-charts',
  path: '/efx-charts',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BasicEchartsRoute = BasicEchartsRouteImport.update({
  id: '/basic-echarts',
  path: '/basic-echarts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LabStreamingDataEchartsRoute = LabStreamingDataEchartsRouteImport.update({
  id: '/lab/streaming-data-echarts',
  path: '/lab/streaming-data-echarts',
  getParentRoute: () => rootRouteImport,
} as any)
const LabStreamingDataRoute = LabStreamingDataRouteImport.update({
  id: '/lab/streaming-data',
  path: '/lab/streaming-data',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplesSalesAnalyticsRoute = ExamplesSalesAnalyticsRouteImport.update({
  id: '/examples/sales-analytics',
  path: '/examples/sales-analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplesPerformanceRoute = ExamplesPerformanceRouteImport.update({
  id: '/examples/performance',
  path: '/examples/performance',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplesOperationsRoute = ExamplesOperationsRouteImport.update({
  id: '/examples/operations',
  path: '/examples/operations',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplesMarketingRoute = ExamplesMarketingRouteImport.update({
  id: '/examples/marketing',
  path: '/examples/marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplesFinancialRoute = ExamplesFinancialRouteImport.update({
  id: '/examples/financial',
  path: '/examples/financial',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/basic-echarts': typeof BasicEchartsRoute
  '/dashboard': typeof DashboardRoute
  '/efx-charts': typeof EfxChartsRoute
  '/efx-charts-streaming': typeof EfxChartsStreamingRoute
  '/layout-echarts': typeof LayoutEchartsRoute
  '/examples/financial': typeof ExamplesFinancialRoute
  '/examples/marketing': typeof ExamplesMarketingRoute
  '/examples/operations': typeof ExamplesOperationsRoute
  '/examples/performance': typeof ExamplesPerformanceRoute
  '/examples/sales-analytics': typeof ExamplesSalesAnalyticsRoute
  '/lab/streaming-data': typeof LabStreamingDataRoute
  '/lab/streaming-data-echarts': typeof LabStreamingDataEchartsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/basic-echarts': typeof BasicEchartsRoute
  '/dashboard': typeof DashboardRoute
  '/efx-charts': typeof EfxChartsRoute
  '/efx-charts-streaming': typeof EfxChartsStreamingRoute
  '/layout-echarts': typeof LayoutEchartsRoute
  '/examples/financial': typeof ExamplesFinancialRoute
  '/examples/marketing': typeof ExamplesMarketingRoute
  '/examples/operations': typeof ExamplesOperationsRoute
  '/examples/performance': typeof ExamplesPerformanceRoute
  '/examples/sales-analytics': typeof ExamplesSalesAnalyticsRoute
  '/lab/streaming-data': typeof LabStreamingDataRoute
  '/lab/streaming-data-echarts': typeof LabStreamingDataEchartsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/basic-echarts': typeof BasicEchartsRoute
  '/dashboard': typeof DashboardRoute
  '/efx-charts': typeof EfxChartsRoute
  '/efx-charts-streaming': typeof EfxChartsStreamingRoute
  '/layout-echarts': typeof LayoutEchartsRoute
  '/examples/financial': typeof ExamplesFinancialRoute
  '/examples/marketing': typeof ExamplesMarketingRoute
  '/examples/operations': typeof ExamplesOperationsRoute
  '/examples/performance': typeof ExamplesPerformanceRoute
  '/examples/sales-analytics': typeof ExamplesSalesAnalyticsRoute
  '/lab/streaming-data': typeof LabStreamingDataRoute
  '/lab/streaming-data-echarts': typeof LabStreamingDataEchartsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/basic-echarts'
    | '/dashboard'
    | '/efx-charts'
    | '/efx-charts-streaming'
    | '/layout-echarts'
    | '/examples/financial'
    | '/examples/marketing'
    | '/examples/operations'
    | '/examples/performance'
    | '/examples/sales-analytics'
    | '/lab/streaming-data'
    | '/lab/streaming-data-echarts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/basic-echarts'
    | '/dashboard'
    | '/efx-charts'
    | '/efx-charts-streaming'
    | '/layout-echarts'
    | '/examples/financial'
    | '/examples/marketing'
    | '/examples/operations'
    | '/examples/performance'
    | '/examples/sales-analytics'
    | '/lab/streaming-data'
    | '/lab/streaming-data-echarts'
  id:
    | '__root__'
    | '/'
    | '/basic-echarts'
    | '/dashboard'
    | '/efx-charts'
    | '/efx-charts-streaming'
    | '/layout-echarts'
    | '/examples/financial'
    | '/examples/marketing'
    | '/examples/operations'
    | '/examples/performance'
    | '/examples/sales-analytics'
    | '/lab/streaming-data'
    | '/lab/streaming-data-echarts'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BasicEchartsRoute: typeof BasicEchartsRoute
  DashboardRoute: typeof DashboardRoute
  EfxChartsRoute: typeof EfxChartsRoute
  EfxChartsStreamingRoute: typeof EfxChartsStreamingRoute
  LayoutEchartsRoute: typeof LayoutEchartsRoute
  ExamplesFinancialRoute: typeof ExamplesFinancialRoute
  ExamplesMarketingRoute: typeof ExamplesMarketingRoute
  ExamplesOperationsRoute: typeof ExamplesOperationsRoute
  ExamplesPerformanceRoute: typeof ExamplesPerformanceRoute
  ExamplesSalesAnalyticsRoute: typeof ExamplesSalesAnalyticsRoute
  LabStreamingDataRoute: typeof LabStreamingDataRoute
  LabStreamingDataEchartsRoute: typeof LabStreamingDataEchartsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/layout-echarts': {
      id: '/layout-echarts'
      path: '/layout-echarts'
      fullPath: '/layout-echarts'
      preLoaderRoute: typeof LayoutEchartsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/efx-charts-streaming': {
      id: '/efx-charts-streaming'
      path: '/efx-charts-streaming'
      fullPath: '/efx-charts-streaming'
      preLoaderRoute: typeof EfxChartsStreamingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/efx-charts': {
      id: '/efx-charts'
      path: '/efx-charts'
      fullPath: '/efx-charts'
      preLoaderRoute: typeof EfxChartsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/basic-echarts': {
      id: '/basic-echarts'
      path: '/basic-echarts'
      fullPath: '/basic-echarts'
      preLoaderRoute: typeof BasicEchartsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/streaming-data-echarts': {
      id: '/lab/streaming-data-echarts'
      path: '/lab/streaming-data-echarts'
      fullPath: '/lab/streaming-data-echarts'
      preLoaderRoute: typeof LabStreamingDataEchartsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/streaming-data': {
      id: '/lab/streaming-data'
      path: '/lab/streaming-data'
      fullPath: '/lab/streaming-data'
      preLoaderRoute: typeof LabStreamingDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples/sales-analytics': {
      id: '/examples/sales-analytics'
      path: '/examples/sales-analytics'
      fullPath: '/examples/sales-analytics'
      preLoaderRoute: typeof ExamplesSalesAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples/performance': {
      id: '/examples/performance'
      path: '/examples/performance'
      fullPath: '/examples/performance'
      preLoaderRoute: typeof ExamplesPerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples/operations': {
      id: '/examples/operations'
      path: '/examples/operations'
      fullPath: '/examples/operations'
      preLoaderRoute: typeof ExamplesOperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples/marketing': {
      id: '/examples/marketing'
      path: '/examples/marketing'
      fullPath: '/examples/marketing'
      preLoaderRoute: typeof ExamplesMarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples/financial': {
      id: '/examples/financial'
      path: '/examples/financial'
      fullPath: '/examples/financial'
      preLoaderRoute: typeof ExamplesFinancialRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BasicEchartsRoute: BasicEchartsRoute,
  DashboardRoute: DashboardRoute,
  EfxChartsRoute: EfxChartsRoute,
  EfxChartsStreamingRoute: EfxChartsStreamingRoute,
  LayoutEchartsRoute: LayoutEchartsRoute,
  ExamplesFinancialRoute: ExamplesFinancialRoute,
  ExamplesMarketingRoute: ExamplesMarketingRoute,
  ExamplesOperationsRoute: ExamplesOperationsRoute,
  ExamplesPerformanceRoute: ExamplesPerformanceRoute,
  ExamplesSalesAnalyticsRoute: ExamplesSalesAnalyticsRoute,
  LabStreamingDataRoute: LabStreamingDataRoute,
  LabStreamingDataEchartsRoute: LabStreamingDataEchartsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
