/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestRouteImport } from './routes/test'
import { Route as StreamingDataEchartsRouteImport } from './routes/streaming-data-echarts'
import { Route as StreamingDataRouteImport } from './routes/streaming-data'
import { Route as LayoutEchartsRouteImport } from './routes/layout-echarts'
import { Route as EfxCharts2RouteImport } from './routes/efx-charts2'
import { Route as EfxChartsRouteImport } from './routes/efx-charts'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BasicEchartsRouteImport } from './routes/basic-echarts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExamplesSalesAnalyticsRouteImport } from './routes/examples/sales-analytics'
import { Route as ExamplesPerformanceRouteImport } from './routes/examples/performance'
import { Route as ExamplesOperationsRouteImport } from './routes/examples/operations'
import { Route as ExamplesMarketingRouteImport } from './routes/examples/marketing'
import { Route as ExamplesFinancialRouteImport } from './routes/examples/financial'

const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const StreamingDataEchartsRoute = StreamingDataEchartsRouteImport.update({
  id: '/streaming-data-echarts',
  path: '/streaming-data-echarts',
  getParentRoute: () => rootRouteImport,
} as any)
const StreamingDataRoute = StreamingDataRouteImport.update({
  id: '/streaming-data',
  path: '/streaming-data',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutEchartsRoute = LayoutEchartsRouteImport.update({
  id: '/layout-echarts',
  path: '/layout-echarts',
  getParentRoute: () => rootRouteImport,
} as any)
const EfxCharts2Route = EfxCharts2RouteImport.update({
  id: '/efx-charts2',
  path: '/efx-charts2',
  getParentRoute: () => rootRouteImport,
} as any)
const EfxChartsRoute = EfxChartsRouteImport.update({
  id: '/efx-charts',
  path: '/efx-charts',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BasicEchartsRoute = BasicEchartsRouteImport.update({
  id: '/basic-echarts',
  path: '/basic-echarts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplesSalesAnalyticsRoute = ExamplesSalesAnalyticsRouteImport.update({
  id: '/examples/sales-analytics',
  path: '/examples/sales-analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplesPerformanceRoute = ExamplesPerformanceRouteImport.update({
  id: '/examples/performance',
  path: '/examples/performance',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplesOperationsRoute = ExamplesOperationsRouteImport.update({
  id: '/examples/operations',
  path: '/examples/operations',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplesMarketingRoute = ExamplesMarketingRouteImport.update({
  id: '/examples/marketing',
  path: '/examples/marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplesFinancialRoute = ExamplesFinancialRouteImport.update({
  id: '/examples/financial',
  path: '/examples/financial',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/basic-echarts': typeof BasicEchartsRoute
  '/dashboard': typeof DashboardRoute
  '/efx-charts': typeof EfxChartsRoute
  '/efx-charts2': typeof EfxCharts2Route
  '/layout-echarts': typeof LayoutEchartsRoute
  '/streaming-data': typeof StreamingDataRoute
  '/streaming-data-echarts': typeof StreamingDataEchartsRoute
  '/test': typeof TestRoute
  '/examples/financial': typeof ExamplesFinancialRoute
  '/examples/marketing': typeof ExamplesMarketingRoute
  '/examples/operations': typeof ExamplesOperationsRoute
  '/examples/performance': typeof ExamplesPerformanceRoute
  '/examples/sales-analytics': typeof ExamplesSalesAnalyticsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/basic-echarts': typeof BasicEchartsRoute
  '/dashboard': typeof DashboardRoute
  '/efx-charts': typeof EfxChartsRoute
  '/efx-charts2': typeof EfxCharts2Route
  '/layout-echarts': typeof LayoutEchartsRoute
  '/streaming-data': typeof StreamingDataRoute
  '/streaming-data-echarts': typeof StreamingDataEchartsRoute
  '/test': typeof TestRoute
  '/examples/financial': typeof ExamplesFinancialRoute
  '/examples/marketing': typeof ExamplesMarketingRoute
  '/examples/operations': typeof ExamplesOperationsRoute
  '/examples/performance': typeof ExamplesPerformanceRoute
  '/examples/sales-analytics': typeof ExamplesSalesAnalyticsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/basic-echarts': typeof BasicEchartsRoute
  '/dashboard': typeof DashboardRoute
  '/efx-charts': typeof EfxChartsRoute
  '/efx-charts2': typeof EfxCharts2Route
  '/layout-echarts': typeof LayoutEchartsRoute
  '/streaming-data': typeof StreamingDataRoute
  '/streaming-data-echarts': typeof StreamingDataEchartsRoute
  '/test': typeof TestRoute
  '/examples/financial': typeof ExamplesFinancialRoute
  '/examples/marketing': typeof ExamplesMarketingRoute
  '/examples/operations': typeof ExamplesOperationsRoute
  '/examples/performance': typeof ExamplesPerformanceRoute
  '/examples/sales-analytics': typeof ExamplesSalesAnalyticsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/basic-echarts'
    | '/dashboard'
    | '/efx-charts'
    | '/efx-charts2'
    | '/layout-echarts'
    | '/streaming-data'
    | '/streaming-data-echarts'
    | '/test'
    | '/examples/financial'
    | '/examples/marketing'
    | '/examples/operations'
    | '/examples/performance'
    | '/examples/sales-analytics'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/basic-echarts'
    | '/dashboard'
    | '/efx-charts'
    | '/efx-charts2'
    | '/layout-echarts'
    | '/streaming-data'
    | '/streaming-data-echarts'
    | '/test'
    | '/examples/financial'
    | '/examples/marketing'
    | '/examples/operations'
    | '/examples/performance'
    | '/examples/sales-analytics'
  id:
    | '__root__'
    | '/'
    | '/basic-echarts'
    | '/dashboard'
    | '/efx-charts'
    | '/efx-charts2'
    | '/layout-echarts'
    | '/streaming-data'
    | '/streaming-data-echarts'
    | '/test'
    | '/examples/financial'
    | '/examples/marketing'
    | '/examples/operations'
    | '/examples/performance'
    | '/examples/sales-analytics'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BasicEchartsRoute: typeof BasicEchartsRoute
  DashboardRoute: typeof DashboardRoute
  EfxChartsRoute: typeof EfxChartsRoute
  EfxCharts2Route: typeof EfxCharts2Route
  LayoutEchartsRoute: typeof LayoutEchartsRoute
  StreamingDataRoute: typeof StreamingDataRoute
  StreamingDataEchartsRoute: typeof StreamingDataEchartsRoute
  TestRoute: typeof TestRoute
  ExamplesFinancialRoute: typeof ExamplesFinancialRoute
  ExamplesMarketingRoute: typeof ExamplesMarketingRoute
  ExamplesOperationsRoute: typeof ExamplesOperationsRoute
  ExamplesPerformanceRoute: typeof ExamplesPerformanceRoute
  ExamplesSalesAnalyticsRoute: typeof ExamplesSalesAnalyticsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/streaming-data-echarts': {
      id: '/streaming-data-echarts'
      path: '/streaming-data-echarts'
      fullPath: '/streaming-data-echarts'
      preLoaderRoute: typeof StreamingDataEchartsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/streaming-data': {
      id: '/streaming-data'
      path: '/streaming-data'
      fullPath: '/streaming-data'
      preLoaderRoute: typeof StreamingDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/layout-echarts': {
      id: '/layout-echarts'
      path: '/layout-echarts'
      fullPath: '/layout-echarts'
      preLoaderRoute: typeof LayoutEchartsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/efx-charts2': {
      id: '/efx-charts2'
      path: '/efx-charts2'
      fullPath: '/efx-charts2'
      preLoaderRoute: typeof EfxCharts2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/efx-charts': {
      id: '/efx-charts'
      path: '/efx-charts'
      fullPath: '/efx-charts'
      preLoaderRoute: typeof EfxChartsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/basic-echarts': {
      id: '/basic-echarts'
      path: '/basic-echarts'
      fullPath: '/basic-echarts'
      preLoaderRoute: typeof BasicEchartsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples/sales-analytics': {
      id: '/examples/sales-analytics'
      path: '/examples/sales-analytics'
      fullPath: '/examples/sales-analytics'
      preLoaderRoute: typeof ExamplesSalesAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples/performance': {
      id: '/examples/performance'
      path: '/examples/performance'
      fullPath: '/examples/performance'
      preLoaderRoute: typeof ExamplesPerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples/operations': {
      id: '/examples/operations'
      path: '/examples/operations'
      fullPath: '/examples/operations'
      preLoaderRoute: typeof ExamplesOperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples/marketing': {
      id: '/examples/marketing'
      path: '/examples/marketing'
      fullPath: '/examples/marketing'
      preLoaderRoute: typeof ExamplesMarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples/financial': {
      id: '/examples/financial'
      path: '/examples/financial'
      fullPath: '/examples/financial'
      preLoaderRoute: typeof ExamplesFinancialRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BasicEchartsRoute: BasicEchartsRoute,
  DashboardRoute: DashboardRoute,
  EfxChartsRoute: EfxChartsRoute,
  EfxCharts2Route: EfxCharts2Route,
  LayoutEchartsRoute: LayoutEchartsRoute,
  StreamingDataRoute: StreamingDataRoute,
  StreamingDataEchartsRoute: StreamingDataEchartsRoute,
  TestRoute: TestRoute,
  ExamplesFinancialRoute: ExamplesFinancialRoute,
  ExamplesMarketingRoute: ExamplesMarketingRoute,
  ExamplesOperationsRoute: ExamplesOperationsRoute,
  ExamplesPerformanceRoute: ExamplesPerformanceRoute,
  ExamplesSalesAnalyticsRoute: ExamplesSalesAnalyticsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
